// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-bio.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_bio_default = defineTool({
  name: "get_bio",
  title: "Get Joseph Maina's bio",
  description: "Returns a short professional bio for Joseph Maina, Digital Marketing Specialist & Agency Owner based in Nairobi, Kenya.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          "Joseph Maina \u2014 Digital Marketing Specialist & Agency Owner based in Nairobi, Kenya.",
          "Services: Meta Ads, Google Ads, TikTok Ads, SEO, Social Media Management, Media Buying.",
          "Focus: Kenyan and African brands \u2014 restaurants, e-commerce, real estate, startups, SMEs.",
          "Website: https://josephmaina.co.ke"
        ].join("\n")
      }
    ]
  })
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var SERVICES = [
  { name: "Meta Ads", description: "Facebook & Instagram advertising campaigns with a focus on ROAS." },
  { name: "Google Ads", description: "Search, Display, YouTube and Performance Max campaigns." },
  { name: "TikTok Ads", description: "TikTok advertising and creator-led performance campaigns." },
  { name: "SEO", description: "Local and technical SEO for Kenyan and African brands." },
  { name: "Social Media Management", description: "Content strategy, community management, and organic growth." },
  { name: "Media Buying", description: "Cross-platform paid media planning and buying." }
];
var list_services_default = defineTool2({
  name: "list_services",
  title: "List services",
  description: "Returns the list of digital marketing services Joseph offers.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SERVICES, null, 2) }],
    structuredContent: { services: SERVICES }
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_contact_default = defineTool3({
  name: "get_contact",
  title: "Get contact info",
  description: "Returns Joseph Maina's public contact information and links to book a free audit.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          "Website: https://josephmaina.co.ke",
          "Location: Nairobi, Kenya",
          "Book a free audit via the contact form on the website."
        ].join("\n")
      }
    ]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "joseph-maina-mcp",
  title: "Joseph Maina Portfolio MCP",
  version: "0.1.0",
  instructions: "Tools for Joseph Maina's digital marketing portfolio. Use `get_bio` for a short bio, `list_services` for the services offered, and `get_contact` for public contact info.",
  tools: [get_bio_default, list_services_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
